from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.chrome.service import Service

# Initialize Chrome WebDriver (replace with Firefox WebDriver if needed)
chromedriver_path = "./chromedriver.exe"  # Adjust for your path
service = Service(chromedriver_path)
driver = webdriver.Chrome(service=service)

def highlight_element(element):
    driver.execute_script("arguments[0].setAttribute('style', 'border: 6px solid black;');", element)
    time.sleep(2)
    driver.execute_script("arguments[0].setAttribute('style', 'border: 0px;');", element)

# Open campus.uno/sjbit
driver.get("https://campus.uno/sjbit")#use ur website link 
driver.maximize_window()
time.sleep(2)

email = driver.find_element(By.XPATH, '//*[@id="LoginId"]')
highlight_element(email)
email.send_keys(" ")	#enter your user name
time.sleep(1)
pwd = driver.find_element(By.XPATH, '//*[@id="Password"]')
highlight_element(pwd)
pwd.send_keys(" ")	#enter your password
time.sleep(1)
proceed = driver.find_element(By.XPATH, '//*[@id="intro"]/div/div/div[2]/section/footer/button')
highlight_element(proceed)
proceed.click()
time.sleep(3)


menu = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/a')
highlight_element(menu)
menu.click()
time.sleep(3)

#notes download
cource = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/ul/li/ul/li[13]/a')
highlight_element(cource)
cource.click()
time.sleep(3)
sepm = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[3]/div[1]/div/a[1]')
highlight_element(sepm)
sepm.click()
time.sleep(3)
dwd = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[3]/div[2]/div[2]/div[5]/a[1]')
highlight_element(dwd)
dwd.click()
time.sleep(3)

#fees payment
menu = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/a')
highlight_element(menu)
menu.click()
time.sleep(1)
feepayment = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/ul/li/ul/li[10]')
highlight_element(feepayment)
feepayment.click()
time.sleep(1)
transaction = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[1]/div/div/div[2]/a')
highlight_element(transaction)
transaction.click()
time.sleep(1)
new = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[1]/div/div/div/a')
highlight_element(new)
new.click()
time.sleep(5)
payment = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[2]/div[5]/div/a[3]')
highlight_element(payment)
payment.click()
time.sleep(5)
amt = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[2]/div[3]/div/input')
highlight_element(amt)
amt.send_keys("1680")
time.sleep(1)
opt = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[2]/div[3]/div/input')
highlight_element(opt)
opt.click()
time.sleep(1)
fee = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[2]/div[4]/div/select/option[2]')
highlight_element(fee)
fee.click()
time.sleep(1)
make_payment = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[2]/div[5]/div/a[1]')
highlight_element(make_payment)
make_payment.click()
time.sleep(1)
note = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[3]/div[1]/div/div[2]/div/input')
highlight_element(note)
note.send_keys("EXAM FEE")
time.sleep(1)
term = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[3]/div[2]/div/input')
driver.execute_script("arguments[0].scrollIntoView();",term)
highlight_element(term)
term.click()
time.sleep(1)
cancel = driver.find_element(By.XPATH, '//*[@id="tab-1"]/div/div[3]/div[3]/div/a[2]')
highlight_element(cancel)
cancel.click()
time.sleep(1)

#check attendence status 
menu = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/a')
highlight_element(menu)
menu.click()
time.sleep(3)
attendence = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/ul/li/ul/li[4]/a')
highlight_element(attendence)
attendence.click()
time.sleep(3)
option = driver.find_element(By.XPATH, '//*[@id="dropdown-class-section"]/button')
highlight_element(option)
option.click()
time.sleep(3)
sem2 = driver.find_element(By.XPATH, '//*[@id="dropdown-class-section"]/div/ul/li[5]/a')
highlight_element(sem2)
sem2.click()
time.sleep(10)
go = driver.find_element(By.XPATH, '//*[@id="btn-go"]')
highlight_element(go)
go.click()
time.sleep(10)

#view proctor system
menu = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/a')
highlight_element(menu)
menu.click()
time.sleep(3)
proctor = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/ul/li/ul/li[19]')
highlight_element(proctor)
proctor.click()
time.sleep(3)
Activities = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[4]/div/div[1]/div/a[1]')
highlight_element(Activities)
Activities.click()
time.sleep(6)
meeting = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[4]/div/div[1]/div/a[2]')
highlight_element(meeting)
meeting.click()
time.sleep(6)
grading = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[4]/div/div[1]/div/a[3]')
highlight_element(grading)
grading.click()
time.sleep(6)
academic = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[4]/div/div[1]/div/a[4]')
highlight_element(academic)
academic.click()
time.sleep(6)
Interaction = driver.find_element(By.XPATH, '/html/body/div[1]/form/div[4]/div/div[1]/div/a[5]')
highlight_element(Interaction)
Interaction.click()
time.sleep(6)

#logout
out = driver.find_element(By.XPATH, '/html/body/nav/div[1]/ul/li/ul/li/ul/li[22]')
highlight_element(out)
out.click()
time.sleep(3)

# Close the browser
driver.quit21